version: '3'
services:
  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
    ports:
      - 3001:3001

  post-service:
    container_name: post-service
    build:
      context: ./post-service
    ports:
      - 3002:3002

  search-service:
    container_name: search-service
    build:
      context: ./search-service
    ports:
      - 3003:3003

  nginx:
    image: nginx:latest
    container_name: api-gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - post-service
      - search-service
