version: "3"
services:
  mysql:
    image: mysql:8
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  # auth-service:
  #   container_name: auth-service
  #   build:
  #     context: ./auth-service
  #   environment:
  #     - DATABASE_URL=mysql://user:userpassword@mysql:3306/realestate
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - app-network

  # post-service:
  #   container_name: post-service
  #   build:
  #     context: ./post-service
  #   environment:
  #     - DATABASE_URL=mysql://user:userpassword@mysql:3306/realestate
  #   ports:
  #     - 3002:3002
  #   networks:
  #     - app-network

  # nginx:
  #   image: nginx:latest
  #   container_name: api-gateway
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - auth-service
  #     - post-service
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: # Volume for MySQL data
  postgres-data: # Volume for Postgres data

